# Hyperparameter Tuning & Advanced Models

## Objectives

- Train advanced machine learning models
- Use Stratified K-Fold Cross Validation
- Track experiments with MLflow
- Tune XGBoost and CatBoost using Optuna
- Compare model performance
- Select the best model

Import Libraries

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import mlflow
import mlflow.sklearn

import optuna

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import joblib

Load Dataset

In [2]:
df = pd.read_csv("../data/processed/clustered_data.csv")

df["y"] = df["y"].map({
    "no":0,
    "yes":1
})

X = df.drop("y", axis=1)

y = df["y"]

Train/Test Split

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    stratify=y,

    random_state=42
)

Load Preprocessor

In [4]:
preprocessor = joblib.load(
    "../models/preprocessor.pkl"
)

print("Preprocessor Loaded Successfully.")

Preprocessor Loaded Successfully.

Stratified K-Fold

In [5]:
cv = StratifiedKFold(

    n_splits=5,

    shuffle=True,

    random_state=42
)

Start MLflow

In [6]:
mlflow.set_experiment("Marketing Campaign Response Modelling")

<Experiment: artifact_location=('file:///d:/Important Files/Marketing Campaign Response '
 'Modelling/notebooks/mlruns/1'), creation_time=1782966817289, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1782966817289, lifecycle_stage='active', name='Marketing Campaign Response Modelling', tags={}, trace_location=None, workspace='default'>

XGBoost Pipeline

In [7]:
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),

    ("classifier",
     XGBClassifier(

         random_state=42,

         eval_metric="logloss",

         use_label_encoder=False
     ))
])

xgb_pipeline.fit(X_train, y_train)

print("XGBoost Model Trained Successfully.")

XGBoost Model Trained Successfully.

XGBoost Predictions

In [8]:
y_pred_xgb = xgb_pipeline.predict(X_test)

y_prob_xgb = xgb_pipeline.predict_proba(X_test)[:, 1]

XGBoost Evaluation

In [9]:
xgb_results = {

    "Model": "XGBoost",

    "Accuracy (%)": accuracy_score(y_test, y_pred_xgb) * 100,

    "Precision (%)": precision_score(y_test, y_pred_xgb) * 100,

    "Recall (%)": recall_score(y_test, y_pred_xgb) * 100,

    "F1 Score (%)": f1_score(y_test, y_pred_xgb) * 100,

    "ROC AUC (%)": roc_auc_score(y_test, y_prob_xgb) * 100
}

pd.DataFrame([xgb_results]).round(2)

     Model  Accuracy (%)  Precision (%)  Recall (%)  F1 Score (%)  ROC AUC (%)
0  XGBoost         90.03          61.71       30.39         40.72        80.17

XGBoost Cross Validation

In [10]:
xgb_cv = cross_val_score(

    xgb_pipeline,

    X,

    y,

    cv=cv,

    scoring="roc_auc",

    n_jobs=-1
)

print(f"Mean ROC AUC (%): {xgb_cv.mean()*100:.2f}")

print(f"Std (%): {xgb_cv.std()*100:.2f}")

Mean ROC AUC (%): 78.94
Std (%): 0.87

MLflow Logging (XGBoost)

In [11]:
with mlflow.start_run(run_name="XGBoost_Baseline"):

    mlflow.log_param("Model", "XGBoost")

    mlflow.log_metric("Accuracy", xgb_results["Accuracy (%)"])
    mlflow.log_metric("Precision", xgb_results["Precision (%)"])
    mlflow.log_metric("Recall", xgb_results["Recall (%)"])
    mlflow.log_metric("F1_Score", xgb_results["F1 Score (%)"])
    mlflow.log_metric("ROC_AUC", xgb_results["ROC AUC (%)"])

print("XGBoost logged successfully.")

XGBoost logged successfully.

Save XGBoost Model

In [12]:
joblib.dump(
    xgb_pipeline,
    "../models/xgboost_model.pkl"
)

print("XGBoost model saved.")

XGBoost model saved.

Evaluation Function

In [13]:
def evaluate_model(model, X_test, y_test):

    y_pred = model.predict(X_test)

    y_prob = model.predict_proba(X_test)[:, 1]

    results = {

        "Accuracy (%)": accuracy_score(y_test, y_pred) * 100,

        "Precision (%)": precision_score(y_test, y_pred) * 100,

        "Recall (%)": recall_score(y_test, y_pred) * 100,

        "F1 Score (%)": f1_score(y_test, y_pred) * 100,

        "ROC AUC (%)": roc_auc_score(y_test, y_prob) * 100

    }

    return results

LightGBM Pipeline

In [14]:
lgbm_pipeline = Pipeline([

    ("preprocessor", preprocessor),

    ("classifier",

     LGBMClassifier(

         random_state=42,

         verbose=-1

     ))

])

lgbm_pipeline.fit(X_train, y_train)

print("LightGBM trained successfully.")

LightGBM trained successfully.

Evaluate LightGBM

In [15]:
lgbm_results = evaluate_model(

    lgbm_pipeline,

    X_test,

    y_test

)

lgbm_results["Model"] = "LightGBM"

pd.DataFrame([lgbm_results]).round(2)

,Accuracy (%),Precision (%),Recall (%),F1 Score (%),ROC AUC (%),Model
0,90.18,65.45,27.16,38.39,81.09,LightGBM

Cross Validation

In [16]:
lgbm_cv = cross_val_score(

    lgbm_pipeline,

    X,

    y,

    cv=cv,

    scoring="roc_auc",

    n_jobs=-1

)

print(f"Mean ROC AUC (%): {lgbm_cv.mean()*100:.2f}")

print(f"Std (%): {lgbm_cv.std()*100:.2f}")

Mean ROC AUC (%): 80.11
Std (%): 0.71

MLflow Logging

In [17]:
with mlflow.start_run(run_name="LightGBM_Baseline"):

    mlflow.log_param("Model", "LightGBM")

    mlflow.log_metric("Accuracy", lgbm_results["Accuracy (%)"])
    mlflow.log_metric("Precision", lgbm_results["Precision (%)"])
    mlflow.log_metric("Recall", lgbm_results["Recall (%)"])
    mlflow.log_metric("F1_Score", lgbm_results["F1 Score (%)"])
    mlflow.log_metric("ROC_AUC", lgbm_results["ROC AUC (%)"])

print("LightGBM logged successfully.")

LightGBM logged successfully.

Save Model

In [18]:
joblib.dump(

    lgbm_pipeline,

    "../models/lightgbm_model.pkl"

)

print("LightGBM Saved.")

LightGBM Saved.

CatBoost Pipeline

In [19]:
cat_pipeline = Pipeline([

    ("preprocessor", preprocessor),

    ("classifier",

     CatBoostClassifier(

         random_state=42,

         verbose=False

     ))

])

cat_pipeline.fit(

    X_train,

    y_train

)

print("CatBoost trained successfully.")

CatBoost trained successfully.

Evaluate CatBoost

In [20]:
cat_results = evaluate_model(

    cat_pipeline,

    X_test,

    y_test

)

cat_results["Model"] = "CatBoost"

pd.DataFrame([cat_results]).round(2)

,Accuracy (%),Precision (%),Recall (%),F1 Score (%),ROC AUC (%),Model
0,90.09,63.27,28.77,39.56,81.23,CatBoost

Cross Validation

In [21]:
cat_cv = cross_val_score(

    cat_pipeline,

    X,

    y,

    cv=cv,

    scoring="roc_auc",

    n_jobs=-1

)

print(f"Mean ROC AUC (%): {cat_cv.mean()*100:.2f}")

print(f"Std (%): {cat_cv.std()*100:.2f}")

Mean ROC AUC (%): 79.96
Std (%): 0.63

CatBoost MLflow

In [22]:
with mlflow.start_run(run_name="CatBoost_Baseline"):

    mlflow.log_param("Model", "CatBoost")

    mlflow.log_metric("Accuracy", cat_results["Accuracy (%)"])
    mlflow.log_metric("Precision", cat_results["Precision (%)"])
    mlflow.log_metric("Recall", cat_results["Recall (%)"])
    mlflow.log_metric("F1_Score", cat_results["F1 Score (%)"])
    mlflow.log_metric("ROC_AUC", cat_results["ROC AUC (%)"])

print("CatBoost logged successfully.")

CatBoost logged successfully.

Save Model

In [23]:
joblib.dump(

    cat_pipeline,

    "../models/catboost_model.pkl"

)

print("CatBoost Saved.")

CatBoost Saved.

Stacking Ensemble

In [24]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

stacking_model = StackingClassifier(

    estimators=[
        ("xgb", xgb_pipeline),
        ("lgbm", lgbm_pipeline),
        ("cat", cat_pipeline)
    ],

    final_estimator=LogisticRegression(max_iter=1000),

    cv=5,
    n_jobs=-1
)

stacking_model.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('xgb',
                                Pipeline(steps=[('preprocessor',
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  ['age',
                                                                                   'campaign',
                                                                                   'pdays',
                                                                                   'previous',
                                                                                   'emp.var.rate',
                                                                                   'cons.price.idx',
                                                                                   'cons.conf.idx',
                                                                                   'euribor3m',
                                                                                   'nr.employed',
                                                                                   'previous_contact',
                                                                                   'multiple_contacts',
                                                                                   'is_senior',
                                                                                   'stable_job',
                                                                                   'summer_contact',
                                                                                   'cluster']),
                                                                                 ('cat',
                                                                                  OneHotEn...
                                                                                   'multiple_contacts',
                                                                                   'is_senior',
                                                                                   'stable_job',
                                                                                   'summer_contact',
                                                                                   'cluster']),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  ['job',
                                                                                   'marital',
                                                                                   'education',
                                                                                   'default',
                                                                                   'housing',
                                                                                   'loan',
                                                                                   'contact',
                                                                                   'month',
                                                                                   'day_of_week',
                                                                                   'poutcome'])])),
                                                ('classifier',
                                                 CatBoostClassifier(random_state=42, verbose=False))]))],
                   final_estimator=LogisticRegression(max_iter=1000),
                   n_jobs=-1)

In [25]:
# Save train-test split for next notebook

X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_frame(name="y").to_csv("../data/processed/y_train.csv", index=False)
y_test.to_frame(name="y").to_csv("../data/processed/y_test.csv", index=False)

print("Train/Test datasets saved successfully.")

Train/Test datasets saved successfully.

In [26]:
import joblib

# Save CatBoost model as final model
joblib.dump(cat_pipeline, "../models/best_model.pkl")

print("Best model saved successfully!")

Best model saved successfully!